const cars = [
    "Choose a Manufacturer...",
    "Acura", 
    "Alfa Romeo", 
    "Aston Martin", 
    "Audi", 
    "Bentley", 
    "BMW", 
    "Buick",
    "Bugatti", 
    "Cadillac",
    "Caterham", 
    "Chevrolet", 
    "Chrysler",
    "Daewoo",
    "Daihatsu", 
    "DeLorean",
    "Dodge", 
    "Ferrari", 
    "FIAT",
    "Fisker", 
    "Ford", 
    "Genesis",
    "Geo", 
    "GMC", 
    "Honda", 
    "Hummer", 
    "Hyundai", 
    "Infiniti", 
    "Isuzu", 
    "Jaguar", 
    "Jeep",
    "Karma",
    "Kia",
    "Koenigsegg", 
    "Lamborghini", 
    "Land Rover", 
    "Lexus", 
    "Lincoln", 
    "Lotus",
    "Lucid", 
    "Maserati",
    "Maybach", 
    "Mazda",
    "McLaren", 
    "Mercedes-Benz", 
    "Mercury", 
    "MINI", 
    "Mitsubishi", 
    "Nissan", 
    "Oldsmobile",
    "Pagani", 
    "Plymouth", 
    "Polestar",
    "Pontiac", 
    "Porsche", 
    "Ram", 
    "Rivian",
    "Rolls-Royce", 
    "Saab", 
    "Saturn", 
    "Scion", 
    "Smart", 
    "Subaru", 
    "Suzuki", 
    "Tesla", 
    "Toyota", 
    "Volkswagen", 
    "Volvo" ]

    export default cars;