const cars = [
    "Choose a Manufacturer...",
    "Acura", 
    "Alfa Romeo", 
    "Aston Martin", 
    "Audi", 
    "Bentley", 
    "BMW", 
    "Buick",
    "Bugatti", 
    "Cadillac", 
    "Chevrolet", 
    "Chrysler",
    "Daewoo",
    "Daihatsu", 
    "Dodge", 
    "Ferrari", 
    "FIAT",
    "Fisker", 
    "Ford", 
    "Genesis",
    "Geo", 
    "GMC", 
    "Honda", 
    "Hummer", 
    "Hyundai", 
    "Infiniti", 
    "Isuzu", 
    "Jaguar", 
    "Jeep",
    "Kia",
    "Koenigsegg", 
    "Lamborghini", 
    "Land Rover", 
    "Lexus", 
    "Lincoln", 
    "Lotus", 
    "Maserati",
    "Maybach", 
    "Mazda",
    "Mclaren", 
    "Mercedes-Benz", 
    "Mercury", 
    "MINI", 
    "Mitsubishi", 
    "Nissan", 
    "Oldsmobile",
    "Pagani", 
    "Plymouth", 
    "Pontiac", 
    "Porsche", 
    "Ram", 
    "Rolls-Royce", 
    "Saab", 
    "Saturn", 
    "Scion", 
    "Smart", 
    "Subaru", 
    "Suzuki", 
    "Tesla", 
    "Toyota", 
    "Volkswagen", 
    "Volvo" ]

    export default cars;