const timezones = [
    {
      "offset": "GMT-12:00",
      "name": "Etc/GMT+12",
      "offsetValue": -12,
      "timeZoneName": "International Date Line West",
      "timeZoneAbbr": "IDLW",
    },
    {
      "offset": "GMT-11:00",
      "name": "Pacific/Midway",
      "offsetValue": -11,
      "timeZoneName": "Nome Time",
      "timeZoneAbbr": "NT",
    },
    {
      "offset": "GMT-11:00",
      "name": "Etc/GMT-11",
      "offsetValue": -11,
      "timeZoneName": "Nome Time",
      "timeZoneAbbr": "NT",
    },  
    {
      "offset": "GMT-10:00",
      "name": "America/Adak",
      "offsetValue": -10,
      "timeZoneName": "Hawaii Standard Time",
      "timeZoneAbbr": "HST",
    },
    {
      "offset": "GMT-09:00",
      "name": "America/Anchorage",
      "offsetValue": -9,
      "timeZoneName": "Alaska Standard Time",
      "timeZoneAbbr": "AKST",
    },
    {
      "offset": "GMT-09:00",
      "name": "Pacific/Gambier",
      "offsetValue": -9,
      "timeZoneName": "Alaska Standard Time",
      "timeZoneAbbr": "AKST",
    },
    {
      "offset": "GMT-08:00",
      "name": "America/Los_Angeles",
      "offsetValue": -8,
      "timeZoneName": "Pacific Standard Time",
      "timeZoneAbbr": "PST",
    },
    {
      "offset": "GMT-08:00",
      "name": "America/Dawson_Creek",
      "offsetValue": -8,
      "timeZoneName": "Pacific Standard Time",
      "timeZoneAbbr": "PST",
    },
    {
      "offset": "GMT-08:00",
      "name": "America/Ensenada",
      "offsetValue": -8,
      "timeZoneName": "Pacific Standard Time",
      "timeZoneAbbr": "PST",
    },
    {
      "offset": "GMT-07:00",
      "name": "America/Denver",
      "offsetValue": -7,
      "timeZoneName": "Mountain Standard Time",
      "timeZoneAbbr": "MST",
    },
    {
      "offset": "GMT-07:00",
      "name": "America/Chihuahua",
      "offsetValue": -7,
      "timeZoneName": "Mountain Standard Time",
      "timeZoneAbbr": "MST",
    },
    {
      "offset": "GMT-06:00",
      "name": "America/Chicago",
      "offsetValue": -6,
      "timeZoneName": "Central Standard Time",
      "timeZoneAbbr": "CST",
    },
    {
      "offset": "GMT-06:00",
      "name": "America/Belize",
      "offsetValue": -6,
      "timeZoneName": "Central Standard Time",
      "timeZoneAbbr": "CST",
    },
    {
      "offset": "GMT-06:00",
      "name": "America/Cancun",
      "offsetValue": -6,
      "timeZoneName": "Central Standard Time",
      "timeZoneAbbr": "CST",
    },
    {
      "offset": "GMT-06:00",
      "name": "Chile/EasterIsland",
      "offsetValue": -6,
      "timeZoneName": "Central Standard Time",
      "timeZoneAbbr": "CST",
    },
    {
      "offset": "GMT-05:00",
      "name": "America/New_York",
      "offsetValue": -5,
      "timeZoneName": "Eastern Standard Time",
      "timeZoneAbbr": "EST",
    },
    {
      "offset": "GMT-05:00",
      "name": "America/Bogota",
      "offsetValue": -5,
      "timeZoneName": "Eastern Standard Time",
      "timeZoneAbbr": "EST",
    },
    {
      "offset": "GMT-05:00",
      "name": "America/Havana",
      "offsetValue": -5,
      "timeZoneName": "Eastern Standard Time",
      "timeZoneAbbr": "EST",
    },    
    {
      "offset": "GMT-04:00",
      "name": "America/Santiago",
      "offsetValue": -4,
      "timeZoneName": "Atlantic Standard Time",
      "timeZoneAbbr": "AST",
    },
    {
      "offset": "GMT-04:00",
      "name": "America/Campo_Grande",
      "offsetValue": -4,
      "timeZoneName": "Atlantic Standard Time",
      "timeZoneAbbr": "AST",
    },
    {
      "offset": "GMT-04:00",
      "name": "America/Glace_Bay",
      "offsetValue": -4,
      "timeZoneName": "Atlantic Standard Time",
      "timeZoneAbbr": "AST",
    },
    {
      "offset": "GMT-04:00",
      "name": "America/Goose_Bay",
      "offsetValue": -4,
      "timeZoneName": "Atlantic Standard Time",
      "timeZoneAbbr": "AST",
    },
    {
      "offset": "GMT-04:00",
      "name": "America/La_Paz",
      "offsetValue": -4,
      "timeZoneName": "Atlantic Standard Time",
      "timeZoneAbbr": "AST",
    },
    {
      "offset": "GMT-04:00",
      "name": "America/Caracas",
      "offsetValue": -4,
      "timeZoneName": "Venezuelan Standard Time",
      "timeZoneAbbr": "VET",
    },
    {
      "offset": "GMT-03:00",
      "name": "America/Sao_Paulo",
      "offsetValue": -3,
      "timeZoneName": "Argentina Time",
      "timeZoneAbbr": "ART",
    },
    {
      "offset": "GMT-03:00",
      "name": "America/Argentina/Buenos_Aires",
      "offsetValue": -3,
      "timeZoneName": "Argentina Time",
      "timeZoneAbbr": "ART",
    },
    {
      "offset": "GMT-03:00",
      "name": "America/Montevideo",
      "offsetValue": -3,
      "timeZoneName": "Argentina Time",
      "timeZoneAbbr": "ART",
    },
    {
      "offset": "GMT-03:00",
      "name": "America/Araguaina",
      "offsetValue": -3,
      "timeZoneName": "Argentina Time",
      "timeZoneAbbr": "ART",
    },
    {
      "offset": "GMT-03:00",
      "name": "America/Godthab",
      "offsetValue": -3,
      "timeZoneName": "Argentina Time",
      "timeZoneAbbr": "ART",
    },
    {
      "offset": "GMT-03:00",
      "name": "America/Miquelon",
      "offsetValue": -3,
      "timeZoneName": "Argentina Time",
      "timeZoneAbbr": "ART",
    }, 
    {
      "offset": "GMT-03:30",
      "name": "America/St_Johns",
      "offsetValue": -3.5,
      "timeZoneName": "Newfounland Standard Time",
      "timeZoneAbbr": "NST",
    },
    {
      "offset": "GMT-02:00",
      "name": "America/Noronha",
      "offsetValue": -2,
      "timeZoneName": "Azores Time",
      "timeZoneAbbr": "AT",
    },
    {
      "offset": "GMT-01:00",
      "name": "Atlantic/Cape_Verde",
      "offsetValue": -1,
      "timeZoneName": "West Africa Time",
      "timeZoneAbbr": "WAT",
    },
    {
      "offset": "GMT",
      "name": "Europe/London",
      "offsetValue": 0,
      "timeZoneName": "Greenwich Mean Time",
      "timeZoneAbbr": "GMT",
    },
    {
      "offset": "GMT",
      "name": "Europe/Belfast",
      "offsetValue": 0,
      "timeZoneName": "Greenwich Mean Time",
      "timeZoneAbbr": "GMT",
    },
    {
      "offset": "GMT",
      "name": "Africa/Abidjan",
      "offsetValue": 0,
      "timeZoneName": "Greenwich Mean Time",
      "timeZoneAbbr": "GMT",
    },
    {
      "offset": "GMT",
      "name": "Europe/Dublin",
      "offsetValue": 0,
      "timeZoneName": "Greenwich Mean Time",
      "timeZoneAbbr": "GMT",
    },
    {
      "offset": "GMT",
      "name": "Europe/Lisbon",
      "offsetValue": 0,
      "timeZoneName": "Greenwich Mean Time",
      "timeZoneAbbr": "GMT",
    },
    {
      "offset": "UTC",
      "name": "UTC",
      "offsetValue": 0,
      "timeZoneName": "Greenwich Mean Time",
      "timeZoneAbbr": "GMT",
    },
    {
      "offset": "GMT+01:00",
      "name": "Europe/Amsterdam",
      "offsetValue": 1,
      "timeZoneName": "Central European Time",
      "timeZoneAbbr": "CET",
    },
    {
      "offset": "GMT+01:00",
      "name": "Africa/Algiers",
      "offsetValue": 1,
      "timeZoneName": "Central European Time",
      "timeZoneAbbr": "CET",
    },
    {
      "offset": "GMT+01:00",
      "name": "Africa/Windhoek",
      "offsetValue": 1,
      "timeZoneName": "Central European Time",
      "timeZoneAbbr": "CET",
    },
    {
      "offset": "GMT+01:00",
      "name": "Atlantic/Azores",
      "offsetValue": 1,
      "timeZoneName": "Central European Time",
      "timeZoneAbbr": "CET",
    },
    {
      "offset": "GMT+01:00",
      "name": "Atlantic/Stanley",
      "offsetValue": 1,
      "timeZoneName": "Central European Time",
      "timeZoneAbbr": "CET",
    },
    {
      "offset": "GMT+01:00",
      "name": "Europe/Belgrade",
      "offsetValue": 1,
      "timeZoneName": "Central European Time",
      "timeZoneAbbr": "CET",
    },
    {
      "offset": "GMT+01:00",
      "name": "Europe/Brussels",
      "offsetValue": 1,
      "timeZoneName": "Central European Time",
      "timeZoneAbbr": "CET",
    },
    {
      "offset": "GMT+02:00",
      "name": "Asia/Jerusalem",
      "offsetValue": 2,
      "timeZoneName": "Eastern European Time",
      "timeZoneAbbr": "EET",
    },
    {
      "offset": "GMT+02:00",
      "name": "Africa/Cairo",
      "offsetValue": 2,
      "timeZoneName": "Eastern European Time",
      "timeZoneAbbr": "EET",
    },
    {
      "offset": "GMT+02:00",
      "name": "Africa/Blantyre",
      "offsetValue": 2,
      "timeZoneName": "Eastern European Time",
      "timeZoneAbbr": "EET",
    },
    {
      "offset": "GMT+02:00",
      "name": "Asia/Beirut",
      "offsetValue": 2,
      "timeZoneName": "Eastern European Time",
      "timeZoneAbbr": "EET",
    },
    {
      "offset": "GMT+02:00",
      "name": "Asia/Damascus",
      "offsetValue": 2,
      "timeZoneName": "Eastern European Time",
      "timeZoneAbbr": "EET",
    },
    {
      "offset": "GMT+02:00",
      "name": "Asia/Gaza",
      "offsetValue": 2,
      "timeZoneName": "Eastern European Time",
      "timeZoneAbbr": "EET",
    },
    {
      "offset": "GMT+03:00",
      "name": "Europe/Moscow",
      "offsetValue": 3,
      "timeZoneName": "Moscow Standard Time",
      "timeZoneAbbr": "MSK",
    },
    {
      "offset": "GMT+03:00",
      "name": "Africa/Addis_Ababa",
      "offsetValue": 3,
      "timeZoneName": "Moscow Time",
      "timeZoneAbbr": "MSK",
    },
    {
      "offset": "GMT+03:00",
      "name": "Asia/Riyadh89",
      "offsetValue": 3,
      "timeZoneName": "Moscow Time",
      "timeZoneAbbr": "MSK",
    },
    {
      "offset": "GMT+03:00",
      "name": "Europe/Minsk",
      "offsetValue": 3,
      "timeZoneName": "Moscow Time",
      "timeZoneAbbr": "MSK",
    },
    {
      "offset": "GMT+03:30",
      "name": "Asia/Tehran",
      "offsetValue": 3.5,
      "timeZoneName": "Iran Standard Time",
      "timeZoneAbbr": "IRST",
    },
    
    {
      "offset": "GMT+04:00",
      "name": "Asia/Dubai",
      "offsetValue": 4,
      "timeZoneName": "Samara Time",
      "timeZoneAbbr": "SAMT",
    },
    {
      "offset": "GMT+04:00",
      "name": "Asia/Yerevan",
      "offsetValue": 4,
      "timeZoneName": "Samara Time",
      "timeZoneAbbr": "SAMT",
    },
    {
      "offset": "GMT+04:30",
      "name": "Asia/Kabul",
      "offsetValue": 4.5,
      "timeZoneName": "Iran Standard Time",
      "timeZoneAbbr": "IDT",
    },
    {
      "offset": "GMT+05:00",
      "name": "Asia/Tashkent",
      "offsetValue": 5,
      "timeZoneName": "Azerbaijan Standard Time",
      "timeZoneAbbr": "ADT",
    },
    {
      "offset": "GMT+05:30",
      "name": "Asia/Kolkata",
      "offsetValue": 5.5,
      "timeZoneName": "India Standard Time",
      "timeZoneAbbr": "IST",
    },
    {
      "offset": "GMT+05:45",
      "name": "Asia/Katmandu",
      "offsetValue": 5.75,
      "timeZoneName": "Nepal Standard Time",
      "timeZoneAbbr": "NST",
    },
    {
      "offset": "GMT+06:00",
      "name": "Asia/Dhaka",
      "offsetValue": 6,
      "timeZoneName": "Central Asia Standard Time",
      "timeZoneAbbr": "CAST",
    },
    {
      "offset": "GMT+06:00",
      "name": "Asia/Yekaterinburg",
      "offsetValue": 6,
      "timeZoneName": "Central Asia Standard Time",
      "timeZoneAbbr": "CAST",
    },
    {
      "offset": "GMT+06:30",
      "name": "Asia/Rangoon",
      "offsetValue": 6.5,
      "timeZoneName": "Myanmar Standard Time",
      "timeZoneAbbr": "MST",
    },
    {
      "offset": "GMT+07:00",
      "name": "Asia/Bangkok",
      "offsetValue": 7,
      "timeZoneName": "South East Asia Standard Time",
      "timeZoneAbbr": "SAST",
    },
    {
      "offset": "GMT+07:00",
      "name": "Asia/Novosibirsk",
      "offsetValue": 7,
      "timeZoneName": "North Central Asia Standard Time",
      "timeZoneAbbr": "NCAST",
    },
    {
      "offset": "GMT+08:00",
      "name": "Asia/Hong_Kong",
      "offsetValue": 8,
      "timeZoneName": "China Standard Time",
      "timeZoneAbbr": "CST",
    },
    {
      "offset": "GMT+08:00",
      "name": "Etc/GMT+8",
      "offsetValue": 8,
      "timeZoneName": "Singapore Standard Time",
      "timeZoneAbbr": "MPST",
    },
    {
      "offset": "GMT+08:00",
      "name": "Asia/Krasnoyarsk",
      "offsetValue": 8,
      "timeZoneName": "North Asia Standard Time",
      "timeZoneAbbr": "NAST",
    },
    {
      "offset": "GMT+08:00",
      "name": "Australia/Perth",
      "offsetValue": 8,
      "timeZoneName": "West Australia Standard Time",
      "timeZoneAbbr": "WAST",
    },
    {
      "offset": "GMT+08:45",
      "name": "Australia/Eucla",
      "offsetValue": 8.75,
      "timeZoneName": "Australian Central Western Standard Time",
      "timeZoneAbbr": "ACWST",
    },
    {
      "offset": "GMT+09:00",
      "name": "Asia/Tokyo",
      "offsetValue": 9,
      "timeZoneName": "Japan Standard Time",
      "timeZoneAbbr": "JST",
    },
    {
      "offset": "GMT+09:00",
      "name": "Asia/Irkutsk",
      "offsetValue": 9,
      "timeZoneName": "North Asia East Standard Time",
      "timeZoneAbbr": "NAEST",
    },
    {
      "offset": "GMT+09:00",
      "name": "Asia/Seoul",
      "offsetValue": 9,
      "timeZoneName": "Korea Standard Time",
      "timeZoneAbbr": "KST",
    },
    {
      "offset": "GMT+09:30",
      "name": "Australia/Adelaide",
      "offsetValue": 9.5,
      "timeZoneName": "Central Australia Standard Time",
      "timeZoneAbbr": "CAST",
    },
    {
      "offset": "GMT+09:30",
      "name": "Australia/Darwin",
      "offsetValue": 9.5,
      "timeZoneName": "Australia Central Standard Time",
      "timeZoneAbbr": "ACST",
    },
    {
      "offset": "GMT+09:30",
      "name": "Pacific/Marquesas",
      "offsetValue": 9.5,
      "timeZoneName": "Marquesas Time",
      "timeZoneAbbr": "MART",
    },
    {
      "offset": "GMT+10:00",
      "name": "Australia/Brisbane",
      "offsetValue": 10,
      "timeZoneName": "East Australia Standard Time",
      "timeZoneAbbr": "EAST",
    },
    {
      "offset": "GMT+10:00",
      "name": "Etc/GMT+10",
      "offsetValue": 10,
      "timeZoneName": "West Pacific Standard Time",
      "timeZoneAbbr": "CAST",
    },
    {
      "offset": "GMT+10:00",
      "name": "Australia/Hobart",
      "offsetValue": 10,
      "timeZoneName": "Tasmania Standard Time",
      "timeZoneAbbr": "TST",
    },
    {
      "offset": "GMT+10:00",
      "name": "Asia/Yakutsk",
      "offsetValue": 10,
      "timeZoneName": "Yakutsk Standard Time",
      "timeZoneAbbr": "YST",
    },
    {
      "offset": "GMT+10:30",
      "name": "Australia/Lord_Howe",
      "offsetValue": 10.5,
      "timeZoneName": "Lord Howe Standard Time",
      "timeZoneAbbr": "LHST",
    },
    {
      "offset": "GMT+11:00",
      "name": "Asia/Vladivostok",
      "offsetValue": 11,
      "timeZoneName": "Vladivostok Standard Time",
      "timeZoneAbbr": "VST",
    },
    {
      "offset": "GMT+11",
      "name": "Pacific/Norfolk",
      "offsetValue": 11,
      "timeZoneName": "Norfolk Time",
      "timeZoneAbbr": "NFT",
    },
    {
      "offset": "GMT+12:00",
      "name": "Pacific/Auckland",
      "offsetValue": 12,
      "timeZoneName": "New Zealand Standard Time",
      "timeZoneAbbr": "NZST",
    },
    {
      "offset": "GMT+12:00",
      "name": "Etc/GMT+12",
      "offsetValue": 12,
      "timeZoneName": "UTC+12",
      "timeZoneAbbr": "U",
    },
    {
      "offset": "GMT+12:00",
      "name": "Asia/Anadyr",
      "offsetValue": 12,
      "timeZoneName": "Magadan Standard Time",
      "timeZoneAbbr": "MST",
    },
    {
      "offset": "GMT+12:00",
      "name": "Asia/Magadan",
      "offsetValue": 12,
      "timeZoneName": "Magadan Standard Time",
      "timeZoneAbbr": "MST",
    },
    {
      "offset": "GMT+12:45",
      "name": "Pacific/Chatham",
      "offsetValue": 12.75,
      "timeZoneName": "Chatham Islands Time",
      "timeZoneAbbr": "CIT",
    },
    {
      "offset": "GMT+13:00",
      "name": "Pacific/Tongatapu",
      "offsetValue": 13,
      "timeZoneName": "Tonga Standard Time",
      "timeZoneAbbr": "TST",
    },
    {
      "offset": "GMT+14:00",
      "name": "Pacific/Kiritimati",
      "offsetValue": 14,
      "timeZoneName": "Line Islands Time",
      "timeZoneAbbr": "LINT",
    }
  ]

  export default timezones;