import React from 'react';
import {Platform, Text, StatusBar, StyleSheet, View, ScrollView, SafeAreaView} from 'react-native'
// import Text from '../../components/Txt'

class PrivacyPolicy extends React.Component{
    componentDidMount(){
        // Set Status Bar page info here!
       this._navListener = this.props.navigation.addListener('didFocus', () => {
           StatusBar.setBarStyle('dark-content', true);
           Platform.OS === 'android' && StatusBar.setBackgroundColor('white');
         });
       }

    render(){
        return(
            <ScrollView style={{backgroundColor: 'white'}}>
                <View style={styles.container}>
                    <Text style={styles.para}>
                    Riive, Inc. (“Riive,” “we,” “us”) takes your privacy very seriously. We provide this Privacy Policy to inform you of our policies and procedures regarding the collection, use and disclosure of personal information we receive from Users of our website at Riive.com (the “Site”) and the Riive iOS mobile device application (the “App”) or any other products provided by Riive, Inc. The Site, App, and all other Riive services are collectively referred to as the “Services.” This Privacy Policy applies only to information that you provide to us through use of the Services or by direct contact with a representative of Riive. By using the Services, you are agreeing to be bound by these policies. Our privacy policy will be updated as necessary. We will notify you of any material changes and all updates to the privacy policy will be posted on the Site and within the Mobile App.</Text>
                    <Text style={styles.head}>Key Terms</Text>
                    <Text style={styles.para}><Text style={styles.underline}>Services</Text>: The website at Riive.com (the “Site”) and the Riive iOS mobile device application (the “App”) or any other products provided by Riive, LLC. The Site, App, and all other Riive services are collectively referred to as the “Services.”</Text>
                    <Text style={styles.para}><Text style={styles.underline}>User</Text>: Any individual who is in contact with the Services, whether registered or not.</Text>
                    <Text style={styles.para}><Text style={styles.underline}>Registered User</Text>: Any individual who has contacted the Services, provided the required information, and completed the steps necessary to create an account.</Text>
                    <Text style={styles.para}><Text style={styles.underline}>Host</Text>: Any Registered User who has created and published a Listing in the Services whether the owner, renter, or employee of the owner of that property.</Text>
                    <Text style={styles.para}><Text style={styles.underline}>Guest</Text>: Any Registered User who uses the Services to seek a parking space, request to utilize a parking space, or complete an exchange of funds with a Host for use of property.</Text>
                    <Text style={styles.para}><Text style={styles.underline}>Listing</Text>: A property which has been input into the Services and offered by a Host for a Guest to utilize.</Text>
                    <Text style={styles.para}><Text style={styles.underline}>Listing</Text>: A property which has been input into the Services and offered by a Host for a Guest to utilize.</Text>
                    <Text style={styles.para}></Text>
                    <Text style={styles.para}><Text style={styles.bold}>Log Data</Text>. Like many websites, we also use automated data collection tools such as “cookies” and “web beacons” to collect certain information. “Cookies” are small text files that we transfer to your computer’s hard disk for record-keeping purposes. We use “persistent cookies” to save your registration ID and login password for future logins to the Site; and we use “session ID cookies” to enable certain features of the Site, to better understand how you interact with the Site and to monitor aggregate usage and web traffic routing on the Site. You can instruct your browser, by changing its options, to stop accepting cookies or to prompt you before accepting a cookie from the websites you visit. If you do not accept cookies, however, you may not be able to use all portions of the Site or all functionality of our Services. Note that this Privacy Policy covers only our use of cookies and does not include use of cookies by third parties.</Text>
                    <Text style={styles.para}><Text style={styles.bold}>Cookies</Text>. Our servers automatically record information about how Users (both account holders and non-account holders) use our Services. This information, referred to as “Log Data,” may include, but is not limited to, your computer’s Internet Protocol address, browser type, operating system, the web page you were visiting before you accessed our Services, the pages or features of our Services that you browsed and the time spent on those pages or features, search terms, the links on our Services that you clicked, and statistics related to your use of the Services. We use Log Data to administer the Services and to analyze (or have third parties analyze) the Log Data to improve, customize, and enhance our Services by expanding their features and functionality and tailoring them to our Users’ needs and preferences.</Text>
                    <Text style={styles.para}><Text style={styles.bold}>Third Parties</Text>. We may also allow third parties, including, but not limited to Google Analytics, to place cookies on the Site. Third parties use these technologies to help us analyze how you use the Site and to market and advertise to you on the Site and third party websites. These cookies also help us detect or prevent fraud or conduct risk assessments, or to collect information about your activities on the Site. To prevent Google Analytics from using your information for analytics, you may install the Google Analytics Opt-Out Browser. To opt out of Google Analytics for display advertising or customize Google display network ads, you can visit the Google Ads Settings page. We do not control any of these opt-out links and are not responsible for the availability or accuracy of these mechanisms.</Text>
                    <Text style={styles.para}><Text style={styles.bold}>Web Beacons</Text>. “Web Beacons” (also known as clear gifs) are tiny graphics with a unique identifier that may be included on our Services for several purposes, including to deliver or communicate with cookies, to track and measure the performance of our Services, to monitor how many visitors view our Services, and to monitor the effectiveness of our advertising. Unlike cookies, which are stored on the User’s hard drive, web beacons are typically embedded invisibly on web pages (or in an email).</Text>
                    <Text style={styles.para}><Text style={styles.bold}>Location Information</Text>. When you use the Services, we may collect and store information about your location by converting your IP address into a geographic location, or by accessing your device’s GPS coordinates or course location if you enable location services on your device. We may use location information to improve and personalize our Services for you. You may opt to not allow us to use your device’s location, but doing so may prevent you from being able to use some or all of features provided by the Services.</Text>
                    <Text style={styles.para}><Text style={styles.bold}>Financial Information</Text>. By using our service, you grant Riive the right, power, and authority to act on your behalf to access and transmit your personal and financial information from the relevant financial institution. You agree to your personal and financial information being transferred, stored, and processed by any third party in accordance with the third party’s Privacy Policy. As a Registered User of the Services, you may be also asked to enter billing information in the form of a Venmo/PayPal account, Apple Pay account, credit or debit card, or other payment method (Payment Info) in order to transact with other Users. You may also be asked to connect your Venmo or bank account in order to receive payment for use of your parking space (Payout Info). You are not required to enter any financial information at any time but you will not have the ability to transact with other Users or collect funds owed to you until you have input the financial information requisite to the task you are attempting to perform. We will inform you when further financial information or other data points are required and request that you provide the data at that time. </Text>
                    <Text style={styles.para}><Text style={styles.bold}>Vehicle Data</Text>. In order to reserve a parking space on your behalf and facilitate transactions between Guests and Hosts, we will request data regarding your vehicle, including make, model, color, year, and license plate number. </Text>
                    <Text style={styles.para}><Text style={styles.bold}>Listing Data</Text>. In order to become a Host, you will be required to create a Listing. In order to create and publish a Listing, you will be required input information specific to the Listing including but not limited to address, property type, business name, business type, property features, and hours of operation.</Text>
                    <Text style={styles.para}><Text style={styles.bold}>User Ratings</Text>. The Services provides a means for other Registered Users to rate your performance and behavior as a Host or Guest. We will aggregate and store this information.</Text>
                    <Text style={styles.para}><Text style={styles.bold}>How We Use PII</Text>. PII is used for the following purposes: (a) to provide and improve our Services, features and content; (b) to administer your account and your use of our Services; (c) to enable Users to enjoy and easily navigate the Site and Mobile Application; (d) to better understand your needs and interests; (e) to fulfill requests you may make; (f) to personalize your experience; (g) to provide or offer software updates and product announcements; and (h) to provide you with further information and offers from us or our partners, and to market, advertise, and inform you about products and services that we may deem relevant to you. These may include products and services offered directly by us or any entity with which we have formed a business relationship. This information and these communications may come to you in the form of email, mobile messaging, telephone contact, or direct mail depending upon the preferences which you indicate to us within your account.</Text>
                    <Text style={styles.para}>If you decide at any time that you no longer wish to receive such communications, please follow the instructions provided in any of the communications or update your “User Settings” information. (See “Changing or Deleting Information,” below.) We use information we obtain by technical means (such as the automatic recording performed by our servers or through the use of cookies) for the above purposes, and in order to monitor and analyze use of the Services for behavioral information and for technical administration of the Services, as well as to increase the functionality and user-friendliness of the Services, to better tailor the Services to your needs, to generate and derive useful data and information concerning the interests, characteristic, website and Mobile App use behavior of our Users, and to verify that visitors to the Services meet the criteria required to process their requests.</Text>
                    <Text style={styles.para}>We have the capability to re-utilize your payment information after you have completed a transaction using the Services for items such as recurring reservations, cancellation fees, and penalty fees as covered in our Terms of Services and Cancellation Policy. These policies are in place to ensure that the Services perform adequately and maintain their value for all Users.</Text>
                    <Text style={styles.head}>Information Sharing and Disclosure</Text>
                    <Text style={styles.para}><Text style={styles.bold}>Information We Disclose With Your Consent or at Your Request</Text>. We will display portions of your PII in your profile page and elsewhere throughout the Services according to the preferences you set in your account. Any information you choose to provide should reflect how much you want all other Riive Users to know about you. We will share your PII with third-party sites or platforms, such as social networking sites, if you have requested that we do so.</Text>
                    <Text style={styles.para}><Text style={styles.bold}>Information Shared to Facilitate Transactions on Your Behalf</Text>. When you utilize the Services to request a parking reservation with a Host, or when you publish your Listing in order to begin accepting reservations, we will share specific data points and PII about you or your Listing with the specific Hosts that you have requested a reservation with or with any Guest who searches for available parking in the area of your Listing. Data shared with other Users may include but is not limited to past User ratings, Listing address, features, and hours, vehicle, make, model, year, and color. Your financial information will not be shared with or made visible to other Users. Your license plate number will not be made visible, but may be used as a blind verification tool. (Example: Host sees your car on his/her property and wants to verify that you are a Guest with an approved reservation. The Host may enter your plate number and the Services will compare their entry to your plate number and inform them whether it is a match or not.)</Text>
                    <Text style={styles.para}><Text style={styles.bold}>Information Shared with Services Providers and Analysts</Text>. We may engage third-party service providers to work with us to administer and provide the Services. These third-party service providers may have access to your PII only for the purpose of performing services on our behalf and are expressly obligated by agreement, statute and/or applicable regulations not to disclose or use your PII for any other purpose. We may share aggregated information and non-identifying information with third parties for purposes that include, but are not limited to, industry research and analysis, demographic profiling, and other similar purposes.</Text>
                    <Text style={styles.para}><Text style={styles.bold}>Information Disclosed in Connection With Business Transactions</Text>. Information that we collect from our Users, including PII, is considered to be a business asset. As a result, if we go out of business, enter bankruptcy, or are acquired as a result of a transaction such as a merger, acquisition, or asset sale, your PII may be disclosed or transferred to the third-party acquirer in connection with the transaction. In such an event we will take the steps we deem appropriate to ensure that your privacy rights remain protected.</Text>
                    <Text style={styles.para}><Text style={styles.bold}>Information Disclosed to Protect Us and Others</Text>. We cooperate with government and law enforcement officials or private parties to enforce and comply with the law. We may disclose any information about you to government or law enforcement officials, or private parties as we, at our sole discretion, believe necessary or appropriate to: (a) respond to claims, or legal process (including subpoenas); (b) protect our property, rights and safety, and the property, rights and safety of a third party or the public in general; and (c) stop any activity that we consider illegal, unethical, or legally actionable.</Text>
                    <Text style={styles.para}><Text style={styles.bold}>Changing or Deleting Your Information</Text>. All Registered Users may review, update, correct, or delete the PII provided in their registration or account profile by contacting us at support@riive.net or by changing their User profile information. If you completely delete all such information, then your account may become deactivated.</Text>
                    <Text style={styles.para}><Text style={styles.bold}>Security</Text>. We take reasonable administrative, physical, and electronic measures designed to protect the information that we collect from or about you (including your PII) from unauthorized access, use or disclosure. Please be aware, however, that no method of transmitting information over the Internet or storing information is completely secure. Accordingly, we cannot guarantee the absolute security of any information. By agreeing to our Terms of Services, you agree to indemnify and hold Riive and any affiliated entities harmless, in the event that your PII is accessed by an unauthorized party as a result of using the Services.</Text>
                    <Text style={styles.para}><Text style={styles.bold}>Our Policy Regarding Children</Text>. The Services are not directed to children under the age of 18. We do not knowingly collect personally identifiable information from children under the age of 18. If a parent or guardian becomes aware that his or her child has provided us with PII without their consent, he or she should contact us at Hello@Riive.com. If we become aware that a child under 18 has provided us with PII, we will delete such information from our files.</Text>
                    <Text style={styles.para}><Text style={styles.bold}>Contacting Us</Text>. If you have any questions about this Privacy Policy, please contact us at support@riive.net.</Text>
                </View>
            </ScrollView>
        )
    }
}

const styles = StyleSheet.create({
    container:{
        width: '90%',
        paddingTop: 20,
        marginHorizontal: '5%',
    },
    para:{
        marginBottom: 10,
    },
    underline:{
        textDecorationLine: 'underline',
    },
    bold:{
        fontWeight: "600",
    }, 
    head:{
        marginVertical: 10,
        fontSize: 18,
        fontWeight: "600",
    }
})

export default PrivacyPolicy;