import React from 'react';
import {Platform, Text, StatusBar, StyleSheet, View, ScrollView, SafeAreaView} from 'react-native'


class TOS extends React.Component{
    componentDidMount(){
        // Set Status Bar page info here!
       this._navListener = this.props.navigation.addListener('didFocus', () => {
           StatusBar.setBarStyle('dark-content', true);
           Platform.OS === 'android' && StatusBar.setBackgroundColor('white');
         });
       }

    render(){
        return(
            <ScrollView style={{backgroundColor: 'white'}}>
                <View style={styles.container}>
                <Text style={styles.para}>Riive provides on an online platform which has the sole purpose of enabling 
                    vehicle owners (“Guests”) and parking space holders (“Hosts”) to connect, 
                    reserve and utilize parking space from one another.
                </Text>
                <Text style={styles.para}>This set of Riive Terms & Conditions (this “Terms & Conditions”) 
                        applies to any and all use of (1) the Riive website at https://www.riive.net and all affiliated websites owned and operated solely by Riive (collectively, the “Riive Site”), (2) the parking reservation services made available by Riive 
                        through the Riive Site, any Riive-branded application for your mobile or other device (each, a “Riive Application”), and any other online properties of Riive 
                        or third parties, as described in Part I below (the “Reservation Services”), and (3) any other services or features made available by Riive through the Riive Site 
                        or any Riive Application. Together, the items in (1) through (3) are referred to herein as the “Services”.
                </Text>
                <Text style={styles.para}>In this Terms & Conditions, “Riive” and “we” mean Riive, Inc., a Delaware C Corp, and/or “User” and “you” mean any User of the Services. This Terms & Conditions incorporates
                 Riive’s standard policies, procedures, and terms and conditions for use of the Services that are referenced by name or by links in this Terms & Conditions (collectively, the “Riive Policies”).
                </Text>
                <Text style={styles.para}>
                By accessing or using the Services or clicking “accept” or “agree” to this Terms & Conditions, (1) you acknowledge that you have read, understand and agree to be bound by this Terms & Conditions, and (2) you represent and warrant that you are at least eighteen (18) years old and are not prohibited by law from accessing or using the Services. THIS TERMS & CONDITIONS CONTAINS, AMONG OTHER THINGS, LIABILITY AND INDEMNITY PROVISIONS AND AN ARBITRATION PROVISION CONTAINING A CLASS ACTION WAIVER.
                </Text>
                <Text style={styles.para}>
                Riive may update or revise this Terms & Conditions (including any Riive Policies) from time to time without any prior notice to User. You agree that you will review this Terms & Conditions periodically. You are free to decide whether or not to accept a modified version of this Terms & Conditions, but accepting this Terms & Conditions, as modified, is required for you to continue using the Services. You may have to click “accept” or “agree” to show your acceptance of any modified version of this Terms & Conditions. If you do not agree to the terms of this Terms & Conditions or any modified version of this Terms & Conditions, your sole recourse is to immediately terminate your use of the Services, in which case you will no longer have access to your Account (as defined below). Except as otherwise expressly stated by Riive, any use of the Services (e.g., to use the Reservation Services) is subject to the version of this Terms & Conditions in effect at the time of use.
                </Text>
                <Text style={styles.head}>
                Key Definitions:
                </Text>
                <Text style={styles.para}>“User”</Text>
                <Text style={styles.para}>Any individual who is in contact with the Services, whether registered or not. All Users are bound by these Terms and Conditions whether registered or not.</Text>
                <Text style={styles.para}>“Registered User”</Text>
                <Text style={styles.para}>Any individual who has contacted the Services provided the required information and completed the steps necessary to create an account.</Text>
                <Text style={styles.para}>“Host”</Text>
                <Text style={styles.para}>Any Registered User who has created and published a Listing in the Services whether the owner, renter or employee of the owner of that property.</Text>
                <Text style={styles.para}>“Guest”</Text>
                <Text style={styles.para}>Any User who uses the Services to seek a parking space, request to utilize a parking space, or complete an exchange of funds with Riive or a Host for use of property.</Text>
                <Text style={styles.para}>“Listing”</Text>
                <Text style={styles.para}>A property which has been input into the Services and offered by a Host for Guests to utilize.</Text>
                <Text style={styles.para}>“Reservation”</Text>
                <Text style={styles.para}>An agreement between a Host and Guest to utilize a Host’s offered Listing for a period of time, and the period of time during which a User’s vehicle is physically present on another User’s property as authorized by the agreement between Host and Guest.</Text>
                <Text style={styles.para}>“Reservation Services”</Text>
                <Text style={styles.para}>The Reservation Services are defined as all tools and features provided to Users for the purposes of searching for, browsing, comparing, requesting or reserving parking spaces listed by other Riive Users as well as those tools/features provided for the purposes of managing, facilitating, editing and carrying out reservations, including payment processing, coupon redemption, messaging between Users, archiving and tracking of past reservations, and reservation activity for the purposes of granting User statuses or conducting loyalty programs, rating and reviewing of other Users and their provided spaces, and publishing of these ratings and reviews for use by other Users, favorite listings, managing of vehicles and payment methods.</Text>
                <Text style={styles.para}>“Host Services”</Text>
                <Text style={styles.para}>The Host Services are defined as all tools and features provided to Users for the purposes of listing and offering property for rent to other Riive Users for temporary vehicle parking. The Host Services includes all tools/features provided for the purposes of managing and editing listing details and listing availability as well as all tools/features provided for the purposes of managing, facilitating, editing and carrying out reservations including payment processing and payout/distribution of funds to Hosts, messaging between Users, archiving and tracking of past reservations and reservation requests, tracking of Host activity and Host performance for the purpose of granting Host statuses, rating of Guests publishing of these ratings for use by other Users, managing of payment methods.</Text>
                <Text style={styles.head}> Part I – Guest Reservation Services</Text>
                <Text style={styles.para}>1. Space Reservation. Riive provides the Reservation Services to Users for the sole purposes of providing Users information on the location and apparent availability of parking and assisting them in securing parking at participating third-party parking locations, including but not limited to private driveways, private garages, public lots and private lots. In response to a User’s online request for a reservation through the Riive Site or a Riive Application, User communicates directly with the applicable individual holding/operating said space (the Host of the Listing) regarding such reservation request. The availability of reservations is determined at the time of a User’s query, and Riive makes no representation or warranty (i) regarding the accuracy of any data (including, but not limited to, reservation availability data) received from any Host. Each Host is an independent third party and is not under the control of Riive. Riive is not a guarantor, agent, or otherwise affiliated with any Host. You acknowledge that each Host may have its own policies, terms, and conditions. Once a reservation request is made by a User through the Riive Site or any Riive Application, the Host with such space will provide confirmation of the Reservation to such User by pre-authorizing the Services to auto accept all reservation requests within specified hours and specified days at the time of request. By using the Reservation Services, you agree to receive reservation confirmations by Riive messaging after requesting a Reservation through the Reservation Services. You may terminate your Registration at any time by emailing Riive at support@riive.net.</Text>
                <Text style={styles.para}>In furtherance of (and not in any limitation of) the above, you hereby acknowledge and agree that notwithstanding the assistance that the Reservation Services provide to you in locating and reserving parking, the ultimate decision to utilize the parking information provided by the Reservation Services and to park at any location remains yours and yours alone, and you hereby agree to assume any risk inherent in utilizing the Reservation Services and/or deciding to actually park at any location. For the avoidance of doubt, Riive does not in any way provide parking services of any kind or operate any parking locations. FURTHER, RIIVE ASSUMES NO RESPONSIBILITY OR LIABILITY FOR 1) THE SAFETY OF ANY PERSON, PROPERTY, OR VEHICLE PARKED AT ANY LOCATION OR 2) THE ACTUAL AVAILABILITY OF PARKING AT ANY LOCATION. USE OF, OR A RESERVATION THROUGH, ANY RIIVE APPLICATION WILL IN NO WAY BE CONSIDERED A WARRANTY, GUARANTEE, OR OTHER REPRESENTATION THAT A SPECIFIC PARKING SPACE IS AVAILABLE AT ANY LOCATION AT ANY GIVEN TIME. RIIVE DISCLAIMS ANY AND ALL LIABILITY FOR DAMAGES, DELAYS, OR OTHER CONSEQUENCES THAT MAY ARISE IF A PARKING SPACE IS UNAVAILABLE, OR IF A RIIVE APPLICATION OTHERWISE ERRS OR MALFUNCTIONS.</Text>
                <Text style={styles.para}>2. Calculation of Parking Rates; Payment Authorization; Taxes. You acknowledge that Riive does not determine parking rates with Hosts to facilitate the booking of Reservations. Riive may make a suggestion to a host, but this is not bound to a host’s value of their space, nor should it reflect the decision of the value of a host’s parking space. The parking rate displayed on the Riive Site or Riive Application is determined solely by the Host and Riive’s fees are in direct relation to the price set by the Host. You agree to pay in full the price displayed on the Services for the total reservation price, which includes the parking rate plus, where applicable, service fees, and taxes at the time of your reservation request.</Text>
                <Text style={styles.para}>All Reservations and other transactions consummated through the Riive Site or a Riive Application will be turned over to the relevant Host, and thereafter, a User may be required to enter into a separate agreement with that relevant Host. You acknowledge and confirm that you are authorized and permitted to use any credit card that you register on the Riive Site or a Riive Application. When you fund a transaction, you agree that Riive is not in any way responsible or liable for the transaction. You acknowledge that Riive may collect taxes for remittance to applicable taxing authorities.</Text>
                <Text style={styles.para}>3. Prices. The price of a parking reservation will be determined by the Host with the legal right to reserve said private location. Prices at each private location may change from time to time and at any time, but any such changes will not affect bookings already accepted by a Riive Application. Despite Riive’s best efforts, some of the parking listed on the Services may be incorrectly priced. Riive is under no obligation to fulfill a Reservation, even after you have been sent confirmation of your Reservation. We do not guarantee that pricing for Reservations will be the best available at the time of reservation or reservation request.</Text>
                <Text style={styles.para}>4. Privacy Policy. Riive is committed to helping you safeguard your privacy online. Each User must review our Riive Privacy Policyfor details about how we collect and use information about the use of Riive’s Services. The Riive Privacy Policy is expressly incorporated herein by reference.</Text>
                <Text style={styles.para}>5. Usage Guidelines. User agrees to use the Reservation Services only to book Reservations for User’s own use. Resale or attempted resale of Reservations is grounds for, among other things, cancellation of your Reservations and termination of your access to the Services. Riive expressly reserves all its rights and remedies under applicable state and federal laws. Riive reserves the right, in its sole discretion, to refuse service, terminate User accounts, remove or edit content, or cancel Reservations. User also agrees not to contact or attempt to contact Hosts by means other than the Services with intent to conduct a rental transaction for a property listed with the Services. You also agree not to use the Services to solicit or offer other Users goods or services of any kind beyond reserving and renting parking spaces.</Text>
                <Text style={styles.para}>6. Cancellations and Violations. By requesting a Reservation, you are agreeing to pay the rate published at that time for the requested period. If you later choose to cancel the Reservation, you agree to be subject to the Riive Cancellation Policywhich is subject to change without notice. You may also receive penalties for failure to remove your vehicle from a Host’s property by the end of the reservation period. Penalties for cancellation or failure to vacate a property at the agreed upon time may include but are not limited to, cash fines to be paid immediately, account suspensions, and negative reviews posted publicly on the Services in association with your account, which will inform and warn other Users of your cancellation or failure to vacate at the agreed upon time. By registering your payment information with the Services, you agree to allow Riive to automatically charge in accordance with these policies. The fees and fines charged may vary. The Riive Cancellation Policy is expressly incorporated herein by reference.</Text>
                <Text style={styles.para}>7. Damage to Person or Property. By consenting to this Terms & Conditions you acknowledge that when you enter into a rental agreement with a Host you are choosing to enter the property offered by the Host for parking at your own discretion. By agreeing to these terms, you acknowledge that Riive is not the owner or operator of any property available for rent via the Services and is not responsible for any damage or loss to property or person that may occur while you are on the Host’s property or engaged in a Reservation with the Host. All parking transactions are entered into at your own risk. We cannot and do not guarantee in any way the security of your vehicle or its contents. It is your responsibility to ensure that your vehicle is properly secured. If your vehicle is damaged while on a Host’s property, you agree to first attempt to resolve the matter with the Host. If the matter cannot be resolved through direct contact with the Host, you may contact the Riive Customer Care Team within 24 hours of the end of your reservation to record your case so that we can assess the situation and offer recourse where Riive, in its sole discretion, deems such necessary. If your vehicle is stolen, contact the police and your insurance provider immediately. Riive does not provide any insurance coverage to a User at any time.</Text>
                <Text style={styles.para}>8. Appointment as Agent. By creating a Listing in the Services and becoming a Host, you appoint Riive as your agent for the purposes of connecting your offered space with Guests in need of parking services and forming binding agreements between you and Guests using the Services. You also appoint as your agent for the collection and distribution of your rental fees and you agree to pay a fee to Riive for every rental transaction for these services.</Text>
                <Text style={styles.para}>9. Legal Right to Rent Property. Riive provides tools and features that enable Hosts to list and rent their property for parking use. By using the Services to list an available parking space for rent, you are attesting that you are the legal owner/operator of the property being offered or have obtained the right to rent out the property. It is your responsibility to be aware of and abide by all local laws, codes, or HOA and neighborhood policies. Riive is in no way responsible for any repercussions stemming from your failure to make yourself aware of and abide by your local laws and regulations.</Text>
                <Text style={styles.para}>10. Honoring of Reservations, Cancellations & Penalties. All Hosts will have the opportunity to approve or decline reservation requests from Users (whether manually at the time of request or by pre-authorizing Riive to automatically approve all requests for the period of the time that the listing is available). Once you have turned on Auto Approve or approved a reservation request manually, you must honor the reservation. If you choose to cancel an approved request, you agree to be subject to the Riive Cancellation & Refund Policywhich is subject to change at Riive’s sole discretion. You also agree that Riive may assess penalties for failure to deliver a reserved parking space to another User. Penalties may include but are not limited to, cash fines to be paid immediately or taken from your future earnings until paid in full, account suspensions and negative reviews posted publicly on the Services in association with your account, which will inform and warn other Users of your cancellation or failure to deliver a reserved parking space. By registering your payment information with the Services, you agree to allow Riive to automatically charge you in accordance with these policies. The fees and fines charged may vary.</Text>
                <Text style={styles.para}>11. Damage to Person or Property. By consenting to this Terms & Conditions you acknowledge that when you enter into a rental agreement with a Guest you are voluntarily granting the renting party consent to enter your property or a property which you have been licensed to operate. Wherever possible Riive will take steps to ensure that Users and their property are safe from damage or harm, but by agreeing to these terms, you acknowledge that Riive is not responsible for any damage or loss to property or person that may occur while Riive Users are on your property or engaged in a parking reservation with you. All parking transactions are entered into at your own risk. We cannot and do not guarantee in any way the security or safety of your property. It is your responsibility to ensure that your property is properly secured. If your property is damaged by another Riive User, you agree to first attempt to resolve the matter with the User. If the matter cannot be resolved through direct contact with the User, you must contact Riive Customer service within 24 hours of the end of the reservation to record your case so that we can assess the situation and offer recourse where possible and where we deem necessary. Riive does not provide any insurance coverage to any User at any time. You are solely responsible for obtaining the required insurance coverage necessary to rent out your property for use by others.</Text>
                <Text style={styles.head}>Part II – Terms for All Services</Text>
                <Text style={styles.para}>12. Access to the Services. At present, the Services are free to access, but in order to access a majority of the features offered in the Services, you will be required to submit basic personal information.</Text>
                <Text style={styles.para}>13. Your Account. You are required to check out as a Guest or create an account with Riive through the Riive Site or Riive Application (“Account”) in order to use the Reservation Services. You are not permitted to register or maintain more than one (1) Account. We reserve the right to suspend or delete your Accounts if we believe that you are maintaining multiple Accounts or believe you have breached this Terms & Conditions in any way. When registering for an Account, you must provide true, accurate, current and complete data about yourself on the Riive registration form. You agree that you will not falsify any information about your identity, or impersonate another identity, or create an account with a fictitious identity. You also agree to promptly update your Account data to keep it true, accurate, current, and complete. You are solely responsible for maintaining the confidentiality of your Account and the information in your Account, and you are solely responsible for all use of your Account, whether or not authorized by you. You agree to immediately notify Riive of any unauthorized use of your Account or any other breach of security related to your use of the Services. Riive will not be liable for any misuse or unauthorized access to any User’s Account.</Text>
                <Text style={styles.para}>14. Communications from Riive. By accepting this Terms & Conditions you agree to receive communications from Riive and the Services. The Riive Applications may use GPS locator capabilities to identify your location at the time of use. Riive may send you SMS text messages to provide you with information regarding the Services or as otherwise described in our Riive Privacy Policy. You hereby consent to receive such SMS text messages and are responsible for any associated charges from your cellular provider. The communication standards for the Services include but are not limited to: Email, SMS, in-app messaging, and web-based browser technology. In order to use the Riive Applications, you must maintain an active account with a carrier of electronic communications through mobile devices and you may not use a prepaid cellular phone to access the Services.</Text>
                <Text style={styles.para}>15. User-Generated Content. The Services provide a platform for Users to create and publish content of their creation. By publishing and displaying content of any kind on the Riive Site or through the Riive Applications you hereby assign and transfer copyright, and all other rights to such content, to Riive. For the avoidance of doubt, we are permitted to use any content posted by you to the Services for any of our business purposes. This right will still apply after the termination of your registration or membership. You may not use the Services for any unlawful purpose or any purpose that violates any local policies, or to publish any content that may, at Riive’s sole discretion, be deemed offensive, inaccurate, misleading, defamatory, fraudulent, or illegal. Users are not entitled to publish any content that could be construed as an advertisement or offer for anything other than parking spaces that fall within this set of Terms & Conditions. Riive reserves the right to remove any content from the Services at any time at our sole discretion and without notice.</Text>
                <Text style={styles.para}>16. Promotional Uses. By accepting these Terms & Conditions you agree to allow Riive to use any of your quotes, photos or videos pertaining to Riive, including images and videos of you, as part of Riive’s media and promotional outreach.</Text>
                <Text style={styles.para}>17. Complaints and Disputes Between Users. In the case of a dispute between you and another User, you agree that you will first attempt to resolve the matter through direct communication, through the Services, with the User. In the event that the dispute cannot be resolved through direct communication, you may file a support ticket and request that Riive assists in resolving the matter. By doing so you authorize Riive to deal with the dispute or complaint as we deem appropriate. You also authorize us to use any and all funds we, or our merchant partners, may be holding on your behalf to resolve the matter. You additionally authorize us to deduct funds from or charge any payment method which you have registered with the Services for any amount up to $350 USD in order to resolve the matter.</Text>
                <Text style={styles.para}>18. Referral Programs and Promotional Offers. Riive may choose to offer limited-time promotional offers or referral rewards programs. In order to be eligible for referral rewards, the Users referred by you must be brand new unregistered Users of the Services. They must also use the exact code given them by you to redeem an introductory offer or must sign up using the email or phone number with which you invited them. They must also complete a transaction as a Host or Guest before they are eligible to receive rewards. The rewards offered may be changed by Riive at any time without notice. All promotional offers, coupon codes, introductory offers, account credits, or rewards may be changed, revoked, denied, or canceled at any time without any notice and at Riive’s discretion, whether already granted to the User or not yet accrued.</Text>
                <Text style={styles.para}>19. Riive Promo/Coupon Code Terms and Conditions. Any Riive promotional code or coupon in any form (the “Code”) issued by Riive is subject to the following terms and conditions (“Promo Terms”). Your receipt and/or redemption of the Code constitute acceptance of an agreement with these Promo Terms. Other terms and conditions may apply to use of the Riive Services. Specifically, without limitation, access to and use of the Service is subject to the Riive Terms & Conditions.</Text>
                <Text style={styles.para}>The Code is only redeemable on the Services. Each Code may only be applied to a User’s account once, and only one may be used per transaction. Codes are void if not obtained through authorized, legitimate channels, or if any part of the code is altered, duplicated, forged, counterfeited, or tampered with in any way or do not contain proper security devices (a “nonconforming Code”). Any attempt to obtain or generate multiple Codes and/or nonconforming Codes and/or to use multiple names, email addresses, phone numbers, and/or any fraudulent or other non-permissible means to obtain or use Codes, as determined by Riive in its sole discretion, will give Riive the right to void the Code and disqualify the User. The Code has no cash value, and cannot be exchanged for cash or credit, except as required by law (in which case the value of the Code is deemed $0.001). The Code cannot be bought or sold and is void if sold or exchanged for compensation. Any unused value will be forfeited. Codes cannot be used for past purchases of Services or offers. Codes are void where prohibited by law.</Text>
                <Text style={styles.para}>If a Code is used in violation of these Terms, or if your use of the Code with the Services otherwise violates the Terms & Conditions, Riive reserves the right to (a) cancel any transaction on the Services; (b) void the value of the Code; and/or (c) charge your credit card for the full value of the Services ordered without the Code applied.</Text>
                <Text style={styles.para}>RIIVE AND ITS RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS MAKE NO WARRANTY, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE WITH RESPECT TO ANY CODE. YOU HEREBY RELEASE RIIVE AND ITS RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS, FROM AND AGAINST ANY AND ALL LIABILITY RELATING TO THESE PROMO TERMS OR THE CODE.</Text>
                <Text style={styles.para}>20. Technical Requirements. Use of the Services requires Internet access through your computer or mobile device. You are responsible for all mobile carrier charges resulting from your use of the Services, including from any notifications provided by the Services. Riive does not guarantee that the Services will be compatible with all devices or will be supported by all mobile carriers. You may be required to have JavaScript (or similar technologies) enabled to use the Riive Site, and some features and portions of the Riive Site (including, but not limited to, making, modifying, or canceling Reservations) may not be accessible with JavaScript disabled. The User interface and functionality may not be the same across all platforms and devices. Your access to the Services may be occasionally restricted or blocked to allow for repairs, maintenance, or the introduction of new features. In these cases, we will attempt to restore access as soon as reasonably possible. Any such interruptions to the Service shall not constitute a breach of these terms by Riive. Riive will not be responsible for any failure or inability to make good on an agreement between and yourself and another User caused by a technical difficulty, connection or communication issue, or any interruption of the Services.</Text>
                <Text style={styles.para}>21. Modifications to Services. Riive reserves the right, in its sole discretion, to modify the Services from time to time and without any prior notice to User, including, without limitation, removing, adding, or modifying portions of the Riive Site, Riive Applications, and/or availability of certain Listings. Riive shall have no liability to you for any of the foregoing actions. If you object to any such changes, your sole recourse shall be to immediately cease using the Services. Continued use of the Services following any such changes shall indicate your acknowledgment of, and consent to, such changes and satisfaction with all the Services.</Text>
                <Text style={styles.para}>22. Intellectual Property Rights and Grant of Rights to User. The features, information, and materials provided and depicted through the Services and on the Riive Site and Riive Application are protected by copyright, trademark, patent and other intellectual property laws, and are the sole property of Riive. All text, graphical content, video, data, and other content made available through the Services (collectively, the “Riive Content”) are provided to User by Riive or its partners or licensors solely to support User’s permitted use of the Services. The Riive Content may be modified from time to time by Riive in its sole discretion and without notice to User. Except as expressly set forth herein, no license, right, or interest is granted to User for any other purpose, and any other use of the Services or the Riive Content by User shall constitute a material breach of this Terms & Conditions. Riive and its partners or licensors retain all rights in and to the Services, Riive Content, and any associated patents, trademarks, copyrights, mask work rights, trade secrets, or other intellectual property rights.</Text>
                <Text style={styles.para}>23. Application License. Subject explicitly to this Terms & Conditions, Riive grants User a non-exclusive, non-transferable, revocable license to use the Riive Applications, in object code form only, on User’s compatible devices, solely to facilitate User’s permitted use of the Services. Users grant to Riive a perpetual, royalty-free, worldwide license to any improvement to or created from, or derivative works based on the Services.</Text>
                <Text style={styles.para}>24. Use Restrictions. The Services and Riive Content are offered solely for User’s personal use for the purposes described in this Terms & Conditions. Any and all other uses are prohibited. You agree not to (and not to allow any third party to): (a) use any robot, spider, scraper, or other automatic or manual device, process, or means to access the Services or copy any Riive Content except as expressly authorized by Riive; (b) take any action that imposes or may impose (in Riive’s sole determination) an unreasonable or a disproportionately large load on the Services or Riive’s infrastructure; (c) utilize any device, software, or routine that will interfere or attempt to interfere with the functionality of the Services; (d) rent, lease, copy, provide access to, or sublicense any portion of the Services or Riive Content to a third party; (e) use any portion of the Services or Riive Content to provide, or incorporate any portion of the Services or Riive Content into, any product or service provided to a third party; (f) reverse engineer, decompile, disassemble, or otherwise seek to obtain the source code or non-public APIs to the Services, except to the extent expressly permitted by applicable law (and then only with advance notice to Riive); (g) modify any Services or Riive Content or create any derivative product from any of the foregoing; (h) remove or obscure any proprietary or other notices contained in the Services or Riive Content; (i) use the Services or Riive Content for any illegal purpose; or (j) publicly disseminate information regarding the performance of the Services or Riive Content or access or use the Services or Riive Content for competitive analysis or benchmarking purposes.</Text>
                <Text style={styles.para}>25. Do Not Use While Driving. You agree, represent, and warrant, so long as you use or access the Services YOU WILL NOT, UNDER ANY CIRCUMSTANCES, ACCESS, VIEW, OR USE THE SERVICES WHILE DRIVING OR OTHERWISE OPERATING A VEHICLE OF ANY KIND (including, without limitation, a car, truck, motorcycle, motor scooter, or bicycle) or operating any dangerous equipment or machinery. You understand that using any handheld device in these circumstances is extremely dangerous, and can result in property damage, physical injuries (including dismemberment), or death. You further agree, represent and warrant, that you will not use or access the Services in any manner that places yourself or any other person at risk of injury, and that you will abide by all traffic laws. While effort is made to assure the accuracy of the information presented to the User, the User is solely responsible for safe driving and for the consequences of decisions as to where to travel, drive, or park. Under no circumstance will any of the Riive Parties (as defined below) assume any responsibility or liability for the consequences of driving decisions made by Users. You agree that no Riive Party shall be liable for any driving decisions made by you or at your suggestion, or for any damages, injury, or other harm caused by your use of or accessing the Services or Riive Content while driving, operating equipment or machinery, or otherwise in a dangerous and unsuitable manner, and you hereby waive any claims or causes of action you may have, now or in the future, arising from or relating to the same. IN THE EVENT THAT ANY PARTY NAMES ANY RIIVE PARTY AS A DEFENDANT IN A CASE INVOLVING YOUR USE OF THE SERVICES WHILE OPERATING A VEHICLE, YOU AGREE TO INDEMNIFY AND HOLD ANY SUCH RIIVE PARTY HARMLESS IN SUCH ACTION.</Text>
                <Text style={styles.para}>26. Government End Users. The Services constitute a “commercial item” as defined at 48 C.F.R. 2.101, consisting of “commercial computer software” and “commercial computer software documentation” as such terms are used in 48 C.F.R. 12.212. Consistent with 48 C.F.R. 12.212 and 48 C.F.R. 227.7202-1 through 227.7202-4, all U.S. Government end Users of any the Services are licensed only as commercial items and with only those rights that are granted to all other Users pursuant to this Terms & Conditions.</Text>
                <Text style={styles.para}>27. Export Control. You may not use, export, or re-export any of the Riive Applications, Riive Content, or other aspects of the Services (or any copy or adaptation of the foregoing) in violation of applicable law, including, without limitation, United States and foreign export laws and regulations. You represent and warrant that you are not located in a country that is subject to a U.S. Government embargo or that has been designated by the U.S. Government as a “terrorist supporting” country and that you are not listed on any U.S. Government list of prohibited or restricted parties.</Text>
                <Text style={styles.para}>28. Termination. Riive may suspend your ability to use all or any element of the Services or may terminate this Terms & Conditions effective immediately, without any notice or explanation. Without limiting the foregoing, Riive may suspend your access to the Services if we believe you to be in violation of any part of this Terms & Conditions (including any associated Riive Policies). After any suspension or termination, you may or may not be granted permission to re-establish an Account, and you may lose access to and be unable to use any points accumulated towards any rewards program (if any) in effect at the time. You agree that Riive shall not be liable to you for any termination of this Terms & Conditions or for any effects of any termination of this Terms & Conditions. You are always free to discontinue your use of the Services at any time. You understand that any termination of your Account may involve deletion of any content you stored in your Account for which Riive will have no liability whatsoever.</Text>
                <Text style={styles.para}>29. Reviews, Comments, Communications and Other Content. We appreciate hearing from you. The Services may permit you to submit reviews, comments, and ratings; send emails and other communications; and submit suggestions, ideas, comments, questions, or other information for publication and distribution to Users and other third parties (“User Content”). You are solely responsible for all User Content you generate (and for your Account generally). Any such User Content must not be illegal, malicious, threatening, obscene, racist, defamatory, libelous, pornographic, infringing of intellectual property rights, promoting of illegal activity or harm to groups and/or individuals, invasive of privacy, false, inaccurate, or otherwise injurious to third parties (including, but not limited to, any content that is copyrighted or subject to third party proprietary rights, including privacy, publicity, trade secret, etc., unless you are the owner of such rights or have the appropriate permission for their rightful owner to specifically submit such content), or otherwise objectionable, and must not consist of or contain software, computer viruses, commercial solicitation, political campaigning, chain letters, mass mailings, any form of “spam” or references to illegal activity, malpractice, purposeful overcharging, false advertising, or health code violations (e.g., foreign objects in food, food poisoning, etc.). You may not use a false email address, impersonate any person or entity, or otherwise mislead as to the origin of User Content. Riive reserves the right (but has no obligation) to monitor, remove, or edit User Content at Riive’s sole discretion, including if the User Content violates this Terms & Conditions (including any associated Riive Policies), but you acknowledge that Riive may not regularly review submitted User Content. If you do submit User Content, please be aware that unless we indicate otherwise, you grant Riive a non-exclusive, perpetual, royalty-free, irrevocable, and fully transferable right to use, modify, reproduce, adapt, translate, publish, create derivative works from, distribute, display, and otherwise exploit such content throughout the world in any media. Riive takes no responsibility and assumes no liability for any User Content submitted by you or any other User or third party.</Text>
                <Text style={styles.para}>You agree to indemnify and hold any Riive Party harmless in the event Riive is named as a defendant in an action related to your User Content and you hereby affirm that we have the right to determine whether any of your User Content submissions are appropriate and comply with this Terms & Conditions, to remove any and/or all of your submissions, and to terminate your Account with or without prior notice. You understand and agree that any liability, loss, or damage that occurs as a result of any of the use of any User Content that you make available or access through your use of the Services is solely your responsibility. Riive is not responsible for any public display or misuse of any User Content. Riive does not, and cannot, pre-screen or monitor all User Content; however, at our discretion, we, or technology or agents we employ, may monitor and/or record your interactions with the Services and your submission(s) of User Content.</Text>
                <Text style={styles.para}>30. Your Representations and Indemnity. You represent and warrant that you own or otherwise control all of the rights to any User Content submitted by you; that all User Content submitted by you is accurate; and that exploitation of such User Content by Riive and its other Users, partners, and licensees will not violate this Terms & Conditions, cause injury to any person or entity, or infringe any third-party rights (including, without limitation, intellectual property rights and rights of privacy or publicity). You will indemnify, hold harmless, and (at Riive’s request) defend Riive, its affiliates, and its and their representatives, agents, directors, managers, officers, employees, and shareholders (collectively, the “Riive Parties”) from and against all claims resulting from (a) any User Content submitted by you, (b) your use of the Services or (c) any breach or alleged breach by you of this Terms & Conditions.</Text>
                <Text style={styles.para}>31. Liability Limitations. TO THE MAXIMUM EXTENT PERMITTED BY LAW, EXCEPT AS EXPRESSLY SPECIFIED BELOW WITH RESPECT TO RIIVE GIFT CARDS AND MERCHANT GIFT CARDS, IN NO EVENT SHALL THE RIIVE PARTIES BE LIABLE FOR ANY INJURIES, LOSSES, CLAIMS, OR DIRECT DAMAGES OR ANY SPECIAL, EXEMPLARY, PUNITIVE, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND, WHETHER BASED IN CONTRACT, TORT, OR OTHERWISE, AND EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, WHICH ARISE OUT OF OR ARE ANY WAY CONNECTED WITH (A) THIS TERMS & CONDITIONS; (B) ANY USE OF THE SERVICES, THE RIIVE CONTENT OR THE USER CONTENT; (C) ANY FAILURE OR DELAY (INCLUDING, BUT NOT LIMITED TO, THE USE OR INABILITY TO USE ANY COMPONENT OF THE RESERVATION SERVICES); OR (D) YOUR VISITATION TO ANY PARKING LOCATION OR THE PERFORMANCE, NON-PERFORMANCE, CONDUCT, OR POLICIES OF ANY HOLDER OR MERCHANT IN CONNECTION WITH THE SERVICES. IN ADDITION, YOU SPECIFICALLY UNDERSTAND AND AGREE THAT ANY THIRD PARTY DIRECTING YOU TO THE RIIVE SITE OR RIIVE APPLICATIONS BY REFERRAL, LINK, OR ANY OTHER MEANS IS NOT LIABLE TO USER FOR ANY REASON WHATSOEVER, INCLUDING, BUT NOT LIMITED TO, DAMAGES OR LOSS ASSOCIATED WITH THE USE OF THE SERVICES OR THE RIIVE CONTENT. RIIVE IS NEITHER AN AGENT OF NOR OTHERWISE ASSOCIATED WITH ANY HOST FOR WHICH A USER HAS MADE A RESERVATION OR UTILIZES ANY COUPON.</Text>
                <Text style={styles.para}>You and Riive understand and agree that the disclaimers, exclusions, and limitations in this Section 19 and in Section 20 below are essential elements of this Terms & Conditions and that they represent a reasonable allocation of risk. In particular, you understand that Riive would be unable to make the Services available to you except on these terms and hereby agree that this Terms & Conditions will survive and apply even if any limited remedy specified in this Terms & Conditions is found to have failed its essential purpose.</Text>
                <Text style={styles.para}>32. Disclaimer of Warranties. THE SERVICES, ALL RIIVE CONTENT, AND ANY OTHER INFORMATION, PRODUCTS AND MATERIALS CONTAINED IN OR ACCESSED THROUGH THE SERVICES ARE PROVIDED TO USER ON AN “AS IS” BASIS AND WITHOUT WARRANTY OF ANY KIND. RIIVE EXPRESSLY DISCLAIMS ALL REPRESENTATIONS, WARRANTIES, CONDITIONS, OR INDEMNITIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, OR NON-INFRINGEMENT, OR ANY WARRANTY ARISING FROM A COURSE OF DEALING, PERFORMANCE OR TRADE USAGE. RIIVE DOES NOT WARRANT THAT YOUR USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE, THAT RIIVE WILL REVIEW THE INFORMATION OR MATERIALS MADE AVAILABLE THROUGH THE SERVICES FOR ACCURACY, THAT IT WILL PRESERVE OR MAINTAIN ANY SUCH INFORMATION OR MATERIALS WITHOUT LOSS, OR THAT RIIVE WILL REVIEW AND POLICE THE USER CONTENT. RIIVE SHALL NOT BE LIABLE FOR DELAYS, INTERRUPTIONS, VIRUSES CONTAINED IN ANY USER CONTENT, THE RIIVE SITE, RIIVE APPLICATION OR ANY RIIVE COMMUNICATION, SERVICE FAILURES OR OTHER PROBLEMS INHERENT IN USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS OR OTHER SYSTEMS OUTSIDE THE REASONABLE CONTROL OF RIIVE.THE FOREGOING DISCLAIMERS APPLY TO THE MAXIMUM EXTENT PERMITTED BY LAW. YOU MAY HAVE OTHER STATUTORY RIGHTS. HOWEVER, THE DURATION OF STATUTORILY REQUIRED WARRANTIES, IF ANY, SHALL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.</Text>
                <Text style={styles.para}>33. Links to/from Third-Party Websites. The Services may contain hypertext links to/from websites operated by parties other than Riive. Such hypertext links are provided for User’s reference only, and Riive does not control such websites and is not responsible for their content. Neither these third-party sites, nor any of the contents thereof or promotions, materials, information, or goods or services available thereon, are in any way investigated, monitored, or checked for accuracy, appropriateness or completeness by Riive. Riive’s inclusion of any hypertext links to/from such websites does not imply any endorsement of the material on such websites or any association with their operators. Riive assumes no liability whatsoever for any such third-party websites or any content, features, products, or services made available through such third-party websites. If you decide to leave the Riive Site or Application, as applicable, and access any such third-party sites or to use or install any third-party applications, software or content, you do so at your own risk and you should be aware that our terms and policies no longer govern. You should review the applicable terms and policies, including privacy and data gathering practices, of any site to which you navigate from the Riive Site (or Riive Application) or relating to any applications you use or install from any such site.</Text>
                <Text style={styles.para}>34. Release. Hosts are solely responsible for their interactions with you and any and all claims, injuries, illnesses, damages, liabilities and costs (“Claims”) suffered by you or any third party as a result of your interaction with or visit to any Host’s Listing. YOU HEREBY RELEASE THE RIIVE PARTIES FROM ANY AND ALL SUCH CLAIMS. IN CONNECTION WITH THE FOREGOING, YOU HEREBY WAIVE ANY CIVIL CODE WHICH STATES DIRECTLY OR INDIRECTLY: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH, IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.” You hereby expressly waive and relinquish all rights and benefits under this section and any law of any jurisdiction of similar effect with respect to the release of any unknown or unsuspected claims you may have against the Riive Parties pertaining to the subject matter of this Section 36.</Text>
                <Text style={styles.para}>34. Notify Us of Infringers. We will respond to allegations of copyright violations in accordance with the Digital Millennium Copyright Act (“DMCA”). In response to a valid notice (as described below), we will remove any allegedly infringing content from the Services and will take reasonable steps to contact the provider of the removed content so that a counter-notification may be filed. Upon receipt of a valid counter-notification, we will evaluate the counter-notification and determine whether to restore the content in question, unless we receive notice from the notification provider that a legal action has been filed seeking a court order to restrain the alleged infringer from engaging in the infringing activity. If you believe any of the Services violate your copyright, notify our copyright agent in writing. The contact information for our copyright agent is at the bottom of this section.</Text>
                <Text style={styles.para}>Copyright infringement notices must: (a) provide your physical or electronic signature; (b) identify the copyrighted work that you believe is being infringed; (c) identify the item that you think is infringing your work and include sufficient information about where the material is located so that we can find it; (d) provide us with a way to contact you, such as your address, telephone number, or email; (e) provide a statement that you believe in good faith that the item you have identified as infringing is not authorized by the copyright owner, its agent, or the law to be used on the Services; (f) provide a statement that the information you provide in your notice is accurate, and that (under penalty of perjury) you are authorized to act on behalf of the copyright owner whose work is being infringed; and (g) be sent to Riive’s copyright agent at the following address:</Text>
                <Text style={styles.para}>Riive, Inc. – Copyright Enforcement{"\n"}430 Partridge Run Road{"\n"}Gibsonia, PA 15044{"\n"}support@riive.net</Text>
                <Text style={styles.para}>36. Severability. If any part of this Terms & Conditions is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and Agreement shall continue in effect</Text>
                <Text style={styles.para}>37. Assignment. This Terms & Conditions, and the rights granted and obligations undertaken hereunder, may not be transferred, assigned or delegated in any manner by a User, but may be freely transferred, assigned, or delegated by Riive.</Text>
                <Text style={styles.para}>38. Waiver. Any waiver of any provision of this Terms & Conditions, or a delay by any party in the enforcement of any right hereunder, shall neither be construed as a continuing waiver nor create an expectation of non-enforcement of that or any other provision or right.</Text>
                <Text style={styles.para}>39. Arbitration and Venue. Any and all controversies, disputes, demands, counts, claims, or causes of action (including the interpretation and scope of this clause) between you and the Riive Parties or their successors or assigns shall exclusively be settled through binding and confidential arbitration in the state of Delaware in their Court of Chancery.</Text>
                <Text style={styles.para}>Arbitration shall be subject to the Federal Arbitration Act and not any state arbitration law. The arbitration shall be conducted before one commercial arbitrator, certified by the American Arbitration Association (“AAA”), with substantial experience in resolving commercial contract disputes. As modified by this Terms & Conditions, and unless otherwise agreed upon by the parties in writing, the arbitration will be governed by the AAA’s  Commercial Arbitration Rules and, if the arbitrator deems them applicable, the Supplementary Procedures for Consumer Related Disputes (collectively, the “Rules and Procedures”).</Text>
                <Text style={styles.para}>You and Riive must abide by the following rules: (a) ANY CLAIMS BROUGHT BY YOU OR RIIVE MUST BE BROUGHT IN THE ‘PARTY’S’ INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING; (b) THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON’S CLAIMS, MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING, AND MAY NOT AWARD CLASS-WIDE RELIEF; (c) the arbitrator shall honor claims of privilege and privacy recognized at law; (d) the arbitration shall be confidential, and neither you nor we may disclose the existence, content or results of any arbitration, except as may be required by law or for purposes of enforcement of the arbitration award; (e) the arbitrator may award any individual relief or individual remedies that are permitted by applicable law; and (f) each side pays its own attorneys’ fees and expenses unless there is a statutory provision that requires the prevailing party to be paid its fees and litigation expenses, and, in such instance, the fees and costs awarded shall be determined by the applicable law.</Text>
                <Text style={styles.para}>Not withstanding the foregoing, either you or Riive may bring an individual action in small claims court. Further, claims of defamation, violation of the Computer Fraud and Abuse Act, and infringement or misappropriation of the other party’s patent, copyright, trademark, or trade secret shall not be subject to this arbitration agreement. Such claims shall be exclusively brought in the state or federal courts located in the state of Delaware. Additionally, notwithstanding this agreement to arbitrate, either party may seek emergency equitable relief before the state or federal courts located in Delaware in order to maintain the status quo pending arbitration, and hereby agree to submit to the exclusive personal jurisdiction of the courts located within Delaware for such purpose. A request for interim measures shall not be deemed a waiver of the right to arbitrate.</Text>
                <Text style={styles.para}>With the exception of subparts (a) and (b) in this Section (prohibiting arbitration on a class or collective basis), if any part of this arbitration provision is deemed to be invalid, unenforceable or illegal, or otherwise conflicts with the Rules and Procedures, then the balance of this arbitration provision shall remain in effect and shall be construed in accordance with its terms as if the invalid, unenforceable, illegal or conflicting part was not contained herein. If, however, either subpart (a) or (b) is found to be invalid, unenforceable or illegal, then the entirety of this arbitration provision shall be null and void, and neither you nor Riive shall be entitled to arbitration. If for any reason a claim proceeds in court rather than in arbitration, the dispute shall be exclusively brought in state or federal court located in Delaware.</Text>
                <Text style={styles.para}>For more information on AAA, the Rules and Procedures, or the process for filing an arbitration claim, you may call AAA at 800-778-7879 or visit the AAA website at http://www.adr.org. </Text>
                <Text style={styles.para}>40. Choice of Law. The Services are operated by a U.S. entity, and this Terms & Conditions is made under and shall be governed by and construed in accordance with the laws of the State of Delaware, consistent with the Federal Arbitration Act, without giving effect to any principles that provide for the application of the law of another jurisdiction.</Text>
                <Text style={styles.para}>41. General Terms. You agree that no joint venture, partnership, or employment relationship exists between you and any of the Riive Parties as a result of agreeing to this Terms & Conditions or use of the Services. Further, no joint venture, partnership, or employment relationship exists between any of the Riive Parties and any Host. Our performance of this Terms & Conditions is subject to existing laws and legal process, and nothing contained in this Terms & Conditions limits our right to comply with law enforcement or other governmental or legal requests or requirements relating to your use of the Services or information provided to or gathered by us with respect to such use. A printed version of this Terms & Conditions and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this Terms & Conditions to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. Fictitious names of companies, products, people, characters, and/or data mentioned within the Services are not intended to represent any real individual, company, product, or event. Any rights not expressly granted herein are expressly reserved.</Text>
                <Text style={styles.para}>42. ACKNOWLEDGMENT. BY USING THE SERVICE OR ACCESSING THE RIIVE SITE OR APPLICATION, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF USE AND AGREE TO BE BOUND BY THEM.</Text>
                <Text style={styles.para}>43. Entire Agreement. Not withstanding any agreements or terms expressly incorporated by reference in this Terms & Conditions, this Terms & Conditions constitutes the entire agreement between the parties. This Terms & Conditions (as it may from time to time be amended, restated, or otherwise modified) supersedes any prior agreements, understandings, or negotiations, whether written or oral.  </Text>
                </View>
            </ScrollView>
            
        )
    }
}

const styles = StyleSheet.create({
    container:{
        width: '90%',
        paddingTop: 20,
        marginHorizontal: '5%',
    },
    para:{
        marginBottom: 10,
    },
    head:{
        marginVertical: 10,
        fontSize: 18,
        fontWeight: "600",
    }
})

export default TOS;