require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

abstract_target 'riive-app' do
  config = use_native_modules!

  # use_modular_headers!

   # Flags change depending on the env values.
  #  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false,
    # :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => FlipperConfiguration.enabled,
    # :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # use_frameworks! :linkage => :static


  # Force pods to match minimum iOS version for React Native
# Fixes build issue on Xcode Cloud where some pods
# Use iOS 12 calls despite being set as iOS 11
def __apply_Xcode_14_3_RC_post_install_workaround(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      current_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      minimum_target = '13.0'
      if current_target.to_f < minimum_target.to_f
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_target
      end
    end
  end
end


  target 'riive' do

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'


  # iOS Permissions Library
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  # pod 'GoogleMaps'
  # pod 'Google-Maps-iOS-Utils'

  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false


  pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'BoringSSL-GRPC', '= 0.0.24', :modular_headers => false
  pod 'gRPC-Core', '= 1.44.0', :modular_headers => false

  # pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :tag => 'v19.4.1'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'RNReactNativeHapticFeedback', :path => '../node_modules/react-native-haptic-feedback'



  target 'riiveTests' do
    inherit! :complete
    # Pods for testing
  end

  target 'riive-development' do
    inherit! :complete
    # Pods for dev environment only
  end

  target 'riive-staging' do
    inherit! :complete
    # Pods for dev staging only
  end

end

    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable these next few lines.
    # use_flipper!
    # post_install do |installer|
    #   flipper_post_install(installer)
    # end
    post_install do |installer|
      react_native_post_install(installer)
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
      __apply_Xcode_14_3_RC_post_install_workaround(installer)
  end
end
